@startuml
title Fermeture d'un passage secret quand un personnage est sur la case


participant MoteurJeu
participant "laby:Labyrinthe" as laby
participant "jeuLaby:LabyJeu" as jeuLaby
participant "traversables:ArrayList<Traversable>" as traversables
participant "traversable:Fermeture" as traversable
participant "passage:PassageSecret" as passage

MoteurJeu -> jeuLaby : update(secondes, clavier)
activate jeuLaby
loop traversables.size()
    jeuLaby -> traversables : get(i)
    activate traversables
    traversables --> jeuLaby : traversable
    deactivate traversables

    jeuLaby -> traversable : persoPresent(laby)
    activate traversable
    traversable -> traversable : action(laby)
    activate traversable
    traversable -> passage : fermer()
    activate passage
    passage --> traversable
    deactivate passage
    traversable --> traversable
    deactivate traversable
    traversable --> jeuLaby
    deactivate traversable
end
    jeuLaby --> MoteurJeu
    deactivate jeuLaby
@enduml
