/*3. Considérer le monstre dans les déplacements du personnage
  - Descriptif :
    - lorsque le jeu évolue, le personnage ne peut pas se déplacer sur la case du monstre.
  - Critères de validation :
    - le monstre constitue un obstacle pour le personnage.
    - le monstre et le personnage ne peuvent pas se trouver sur la même case.
    - le personnage ne peut pas traverser la case du monstre
    */

@startuml
title Considérer le monstre dans les déplacements du personnage

participant "perso:Perso" as perso
participant "monstre:Monstre" as monstre
participant "labyjeu:LabyJeu" as labyjeu

activate perso
perso -> labyjeu: deplacerPerso()
activate labyjeu
labyjeu -> monstre: êtrePresent()
activate monstre
monstre --> labyjeu: boolean
deactivate monstre

alt Case du monstre occupée
labyjeu --> perso: êtrePresent() == true
else Case libre
labyjeu --> perso: êtrePresent() == false

perso -> labyjeu: deplacerPerso()

end
deactivate labyjeu

deactivate perso
@enduml