@startuml
title Sortie du labyrinthe

participant "jeuLaby: LabyJeu" as jeuLaby
participant "laby:Labyrinthe" as laby
participant "sortie:Sortie" as sortie
participant "pj:Perso" as pj


jeuLaby -> jeuLaby : etreFini()
activate jeuLaby
jeuLaby -> sortie: sortiePossible()
activate sortie
sortie -> sortie: persoPresent(x,y)
activate sortie
sortie --> sortie :true
deactivate sortie
sortie -> pj: possedeAmulette()
activate pj
pj --> sortie: true
deactivate pj
sortie --> jeuLaby: true
deactivate sortie
jeuLaby --> jeuLaby : true
deactivate jeuLaby

@enduml