@startuml
title Attaque directionnelle

participant "jeuLaby: LabyJeu" as jeuLaby
participant "laby:Labyrinthe" as laby
participant "pj:Perso" as pj
participant "entites:ArrayList<Entite>" as entites


jeuLaby -> laby : attaqueDirectionnel(String : derniereAction)
activate laby
laby -> pj: getX()
activate pj
pj --> laby: x
deactivate pj

laby -> pj: getY()
activate pj
pj --> laby: y
deactivate pj

laby -> laby: getSuivant(int: x, int: y,String: derniereAction)
activate laby
laby --> laby: suivant
deactivate laby

loop entites.size()
    laby -> entites: get(int: i)
    activate entites
    entites --> laby: entite
    deactivate entites

    alt entite.etrePresent(suivant)
        laby -> pj : attaquer(Entite: entite)
        activate pj
        pj -> entite: subirDegat(int: degat)
        activate entite
        entite --> pj
        deactivate entite
        pj --> laby
        deactivate pj
    end
end

laby --> jeuLaby
deactivate laby

@enduml