@startuml
title Utilisation cle pour ouvrir coffre

participant "jeuLaby: LabyJeu" as jeuLaby
participant "laby:Labyrinthe" as laby
participant "coffres:List<Coffre>" as coffres
participant "coffre:Coffre" as coffre
participant "pj: Perso" as pj


alt clavier.e
jeuLaby -> laby: actionnerItem(String: derniereDirection)
activate laby
laby -> laby: getSuivant(x: int, y: int, direction: String)
activate laby
laby --> laby: suivant
deactivate laby

loop coffres.size()
    laby -> coffres: get(i)
    activate coffres
    coffres --> laby: coffre
    deactivate coffres

    laby -> coffre : etrePresent(suivant)
    activate coffre
    coffre --> laby: present
    deactivate coffre

    alt present
        laby -> coffre: action()
        activate coffre
        coffre -> pj: possedeCle()
        activate pj
        pj --> coffre: possede
        deactivate pj

        alt possede
            coffre -> pj: utiliserCle()
            activate pj
            pj --> coffre
            deactivate pj
        end
        coffre --> laby
        deactivate coffre
    end
end
end
laby --> jeuLaby
deactivate laby

@enduml