@startuml
title Avancée d'une flèche

participant "jeuLaby: LabyJeu" as jeuLaby
participant "arc:Arc" as arc
participant "fleche:Fleche" as fleche
participant "laby:Labyrinthe" as laby


jeuLaby -> arc: avancerFleches()
activate arc
arc -> fleche: avancer()
activate fleche
fleche --> laby:getSuivant(x,y)
activate laby
laby --> fleche: suivant
deactivate laby

fleche -> laby:estVideCase(suivant)
activate laby
laby --> fleche: vide
deactivate laby

alt vide
    fleche -> fleche: setX(suivant[0])
    activate fleche
    fleche --> fleche
    deactivate fleche
    fleche -> fleche: setY(suivant[1])
    activate fleche
    fleche --> fleche
    deactivate fleche
end

fleche -> arc: avancee: boolean
deactivate fleche

arc -> jeuLaby
deactivate arc

@enduml